SRC/Applications/HomePage.Web/Views/Shared/Components/Footer/FooterViewComponent.cs
using Homepage.UI.Interfaces;
using HomePage.Web.Infrastructure;
using HomePage.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomePage.Web.Views.Shared.Components.Footer
{
	public class FooterViewComponent : BaseViewComponent
	{
		private readonly IPostHomepageQueries _postHomepageQueries = null;
		private readonly ITopicHomepageQueries _topicHomepageQueries = null;
		private readonly IPageHomepageQueries _pageHomepageQueries = null;



		public FooterViewComponent(IPostHomepageQueries postHomepageQueries,
			ITopicHomepageQueries topicHomepageQueries,
			IStringLocalizer<SharedResource> localizer,
			IPageHomepageQueries pageHomepageQueries) : base(localizer)
		{
			this._postHomepageQueries = postHomepageQueries;
			_topicHomepageQueries = topicHomepageQueries;
			_pageHomepageQueries = pageHomepageQueries;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var model = $"{DateTime.Now.ToString()}";
			var c = CurrentLanguage;

			var footerVm = new FooterViewModel();

			footerVm.Topics = await _topicHomepageQueries.GetAllTopic(condition: "t.is_footer = 1");
			footerVm.Pages = await _pageHomepageQueries.GetAllPage(condition: "p.is_footer = 1");
			return await Task.FromResult((IViewComponentResult)View("_FooterLayout", footerVm));
		}
	}
}

SRC/Applications/HomePage.Web/Views/Shared/Components/Header/HeaderViewComponent.cs
using Homepage.UI.Interfaces;
using HomePage.Web.Infrastructure;
using HomePage.Web.Models;
using MDM.UI.Categories.Interfaces;
using MDM.UI.Categories.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomePage.Web.Views.Shared.Components.Footer
{
    public class HeaderViewComponent : BaseViewComponent
    {
        private readonly ICategoryQueries _categoryQueries;

        public HeaderViewComponent(
            IStringLocalizer<SharedResource> localizer,
            ICategoryQueries categoryQueries) : base(localizer)
        {
            _categoryQueries = categoryQueries;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            IEnumerable<CategoryViewModel> categories = (await _categoryQueries.GetsWithChild(CurrentLanguage))
                .OrderByDescending(x => x.Childs.Count())
                .ToList();

            return View(categories);
        }
    }
}

SRC/Applications/HomePage.Web/Views/Shared/_FooterLayout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<SharedResource> L


<footer class="footerWidget">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 widgetWrap">
                <div class="widget_inner">
                    <div class="logo_descr com_name" style="font-size:20px;">@L["Index_Company_Name"]</div>
                    <br />
                    <h5 class="title">@L["Index_Contact"]</h5>

                    <i class="fa fa-home fa-1x" aria-hidden="true">
                        <strong>@L["Headquarter"]:</strong>
                    </i>
                    <span style="font-size:14px;">
                        @L["Company_Address_Home"]
                    </span>
                    <br />
                    <i class="fa fa-map-marker fa-1x" aria-hidden="true">
                        <strong>@L["Office"]:</strong>
                    </i>
                    <span style="font-size:14px;">
                        @L["Index_Company_Address"]
                    </span>
                    <br />
                    <i class="fa fa-phone-square fa-1x" aria-hidden="true">
                        Hotline:
                    </i>
                    <span style="font-size:14px;">
                        @L["Index_Company_Phone"]
                    </span>

                </div>
            </div>
            <div class="col-sm-3 col-sm-offset-1 widgetWrap">
                <h5 class="title">@L["footer_Aritnt"]</h5>
                <ul>
                    <li>
                        <a href="@L["R.About"]" style="text-decoration:none;">Về chúng tôi</a>
                    </li>
                    <li>
                        <a href="/home/value" style="text-decoration:none;">Sứ mệnh và giá trị</a>
                    </li>
                    <li>
                        <a href="@L["R.Media"]" style="text-decoration:none;">Truyền thông</a>
                    </li>
                    <li>
                        <a href="https://www.careerlink.vn/viec-lam/k/aritnt" style="text-decoration:none;">Tuyển dụng</a>
                    </li>
                    <li>
                        <a href="@L["R.Faqs"]" style="text-decoration:none;">Các câu hỏi thường gặp</a>
                    </li>
                    <li>
                        <a href="@L["R.Trace"]" style="text-decoration:none;">Hướng dẫn đặt hàng</a>
                    </li>
                    <li>
                        <a href="@L["R.Contact"]" style="text-decoration:none;">Liên hệ với chúng tôi</a>
                    </li>
                    <li>
                        <a href="@L["R.Trace"]" style="text-decoration:none;">Truy xuất nguồn gốc</a>
                    </li>
                    <li>
                        <a href="@L["R.FarmerNetwork"]" style="text-decoration:none;">
                            Mạng lưới người nông dân Việt
                        </a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-2 widgetWrap">
                <h5 class="title">@L["footer_Blog"]</h5>
                <ul>
                    <li>
                        <a href="@L["R.GreenSpiritGreenLife"]" style="text-decoration:none;">Tinh thần xanh, Cuộc sống xanh</a>
                    </li>
                    <li>
                        <a href="@L["R.GreenFarming"]" style="text-decoration:none;">Canh tác xanh</a>
                    </li>
                    <li>
                        <a href="@L["R.Travel"]" style="text-decoration:none;">Tản mạn</a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-2 widgetWrap">
                <h5 class="title">@L["footer_PaymentMethod"]</h5>
                <ul>
                    <img src="~/images/payment.png" height="155" width="340">
                </ul>
                <ul>
                    <img src="~/images/bocongthuong.png" height="88" width="253">
                </ul>
            </div>

        </div>
        <div class="row">
            <div class="col-sm-4">
                &copy; @L["Copyright"]
            </div>
        </div>
    </div>
</footer>

SRC/Applications/HomePage.Web/Views/Shared/_GoogleMapApiScriptReference.cshtml
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTbrZ05VWqhwG7ASkrp-WnEL9FNV_4bjE&callback=initMap">
</script>


@*<script>
    var requestGeocodingAPI = "https://maps.googleapis.com/maps/api/geocode/json?address={Address}&key=AIzaSyDTbrZ05VWqhwG7ASkrp-WnEL9FNV_4bjE";
    var geocoder;
    function initMapWithDraggableMarker(lat, lon, mapContainerId) {
        lat = lat == undefined ? 10.768451 : lat;
        lon = lon == undefined ? 106.6943626 : lon;
        var uluru = { lat: lat, lng: lon };
        var mapOptions = {
            zoom: 14,
            center: uluru
        }
        var map = new google.maps.Map(document.getElementById(mapContainerId), mapOptions);

        // Place a draggable marker on the map
        var marker = new google.maps.Marker({
            position: uluru,
            map: map,
            draggable: true,
            title: "Choose the right place"
        });

        google.maps.event.addListener(marker, 'dragend', function (event) {
            document.getElementById("Lat").value = this.getPosition().lat();
            document.getElementById("Lon").value = this.getPosition().lng();
        });
    }
</script>*@

SRC/Applications/HomePage.Web/Views/Shared/_HeaderHtmlLayout.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="format-detection" content="telephone=no">

    <link rel="icon" href="~/images/favicon.png">
    <link rel='stylesheet' href='~/js/vendor/woocommerce/css/select2.css' type='text/css' media='all' />
    <link rel='stylesheet' href='~/js/vendor/woocommerce/css/woocommerce-layout.css' type='text/css' media='all' />
    <link rel='stylesheet' href='~/js/vendor/woocommerce/css/woocommerce-smallscreen.css' type='text/css' media='only screen and (max-width: 768px)' />
    <link rel='stylesheet' href='~/js/vendor/woocommerce/css/woocommerce.css' type='text/css' media='all' />
    <link rel='stylesheet' href='~/css/woo-style.css' type='text/css' media='all' />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto|Roboto+Condensed">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/datetime-picker/bootstrap-datetimepicker.min.css" />
    <link rel='stylesheet' href='~/js/vendor/swiper/idangerous.swiper.css' type='text/css' media='all' />
    <link rel='stylesheet' href='~/js/vendor/swiper/idangerous.swiper.scrollbar.css' type='text/css' media='all' />
    <link rel='stylesheet' href='~/js/vendor/magnific-popup/magnific-popup.css' type='text/css' media='all' />
    <link rel='stylesheet' href='~/css/fontello/css/fontello.css' type='text/css' media='all' />
    <link rel='stylesheet' href='~/css/fontello/css/animation.css' type='text/css' media='all' />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel='stylesheet' href='~/css/style.css' type='text/css' media='all' />
    <link rel='stylesheet' href='~/css/shortcodes.css' type='text/css' media='all' />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" media='all'>
    <link rel='stylesheet' href='~/css/responsive.css' type='text/css' media='all' />
    <link rel='stylesheet' href='~/css/custom_style.css' type='text/css' media='all' />
    <script type='text/javascript' src='~/js/vendor/jquery-1.11.3.min.js'></script>
</head>

SRC/Applications/HomePage.Web/Views/Shared/_HeaderLayout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<SharedResource> L


<header id="header">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand logo" href="~/">
                    <img alt="Brand" src="~/images/logo_220_82.jpg">
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right group-top-right">
                    @*<li>
                        <div class="form-group">
                            <form asp-action="SearchAsync" asp-controller="Home" method="get">
                                <div class="input-group">
                                    <input type="text" class="form-control input-sm" placeholder="Search" id="search" name="searchString">
                                    <div class="input-group-btn">
                                        <button class="btn btn-default btn-sm" id="btn-search">
                                            <i class="glyphicon glyphicon-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>

                    </li>*@
                    <partial name="_SelectLanguagePartial" />
                </ul>

                <ul id="menubar" class="nav navbar-nav navbar-right">
                    <li class="mn-main">
                        <a class="mn-text" href="~/">@L["Index_Homepage"]</a>
                    </li>
                    @*<li class="mn-main dropdown panel-sm">
                <a class="mn-text" href="javascript:void(0)">@L["Index_Introduce"]</a>
                <div class=" icon-collapse">
                    <i class="fa fa-chevron-right fa-lg" aria-hidden="true" data-toggle="collapse" data-target="#introduceMenu"></i>
                </div>
                <ul id="introduceMenu" class="dropdown-menu collapse">
                    <li><a href="@L["R.About"]">@L["Index_AboutUs"]</a></li>
                    <li><a href="@L["R.Gifts"]">@L["Index_Gifts"]</a></li>
                </ul>
            </li>*@
                    <li class="mn-main has-panel">
                        <a class="mn-text" href="javascript:void(0)" style="cursor:default">@L["Index_Product"]</a>
                        <div class=" icon-collapse">
                            <i class="fa fa-chevron-right fa-lg" aria-hidden="true" data-toggle="collapse" data-target="#categoryMenu"></i>
                        </div>
                        <div id="categoryMenu" class="container panel-menu collapse"></div>
                    </li>
                    <li class="mn-main has-panel">
                        <a class="mn-text" href="@L["R.WhereToBuy"]">@L["Index_WhereToBuy"]</a>
                    </li>

                    <li class="mn-main"><a class="mn-text" href="@L["R.Gifts"]">@L["Index_Gifts"]</a></li>

                    <li class="mn-main"><a class="mn-text" href="@L["R.Recipes"]">@L["Index_Recipe"]</a></li>

                    <li class="mn-main"><a class="mn-text" href="@L["R.WeWork"]">@L["Index_Event"]</a></li>
                </ul>

            </div><!--/.nav-collapse -->
        </div>
    </nav>
</header>

SRC/Applications/HomePage.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@using System.Collections.Generic;
@inject IHtmlLocalizer<SharedResource> L

<!DOCTYPE html>
<html>
<partial name="_HeaderHtmlLayout" />

<body class="woocommerce woocommerce-page">
    <div id="wrap" class="wrap fullWidth">
        <div id="wrapBox" class="wrapBox">
            @*<partial name="_HeaderLayout" />*@
            @(await Component.InvokeAsync("Header"))

            @if ((string)ViewData["HasSlider"] == "true")
            {
                <partial name="_SliderLayout" />
            }
            <div class="wrapContent">
                <div id="wrapWide" class="wrapWide">
                    <div class="content" style="margin-left:5%; max-width:90%;">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
    @*<partial name="_FooterLayout" />*@
    @(await Component.InvokeAsync("Footer"))
    <div class="buttonScrollUp upToScroll icon-up-open-micro"></div>


    <partial name="_ScriptsLayout" />
    @RenderSection("Scripts", required: false)
</body>
</html>

SRC/Applications/HomePage.Web/Views/Shared/_ScriptsLayout.cshtml
<script type='text/javascript' src='~/js/vendor/jquery-1.11.3.min.js'></script>
<script type='text/javascript' src='~/js/vendor/jquery-migrate.min.js'></script>
<script src="~/js/custom/jquery.cookie.js"></script>
<script type='text/javascript' src='~/js/vendor/__packed.js'></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="~/js/vendor/parsley.min.js"></script>
<script type='text/javascript' src='~/js/custom/_utils.js'></script>
<script src="~/js/custom/_front.js"></script>
<script type='text/javascript' src='~/js/custom/shortcodes_init.js'></script>
<script type='text/javascript' src='~/js/custom/__main.js'></script>
<script type='text/javascript' src='~/js/custom/common.js'></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/lib/datetime-picker/bootstrap-datetimepicker.js"></script>
<script src="~/js/Blog.js"></script>

SRC/Applications/HomePage.Web/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
    var returnUrl = (string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}")
        + (Context.Request.QueryString.HasValue ? Context.Request.QueryString.Value : "");
    var lang = requestCulture.RequestCulture.UICulture.Name;
}
@{
    var domainHost = Url.ActionContext.HttpContext.Request.Host.Host;
    //var domainHost = ".vn";
}
<li class="usermenuFlag">
    <div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
        <form id="selectLanguage" asp-controller="Home"
              asp-action="SetLanguage" asp-route-returnUrl="@returnUrl"
              method="post" class="form-horizontal" role="form">
            @if (!domainHost.Contains(".vn"))
            {
                if (lang.ToLower() == HomePage.Web.Localization.Languages.Vietnamese.ToLower())
                {
                    <input name="culture" value="@HomePage.Web.Localization.Languages.English" hidden />
                    <button class="btn-lang" style="background: url(/images/flag-vi.png)" disabled></button>
                    <button class="btn-lang" style="background: url(/images/flag-en.png)" onclick="this.form.submit();"></button>
                }
                else
                {
                    <input name="culture" value="@HomePage.Web.Localization.Languages.Vietnamese" hidden />
                    <button class="btn-lang" style="background: url(/images/flag-vi.png)" onclick="this.form.submit();"></button>
                    <button class="btn-lang" style="background: url(/images/flag-en.png)" disabled></button>
                }
            }
        </form>
    </div>
</li>

SRC/Applications/HomePage.Web/Views/Shared/_SliderLayout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IHtmlLocalizer<SharedResource> L

<section class="" style="margin:0; padding:0">
    <div class="container-fluid" style="margin:0; padding:0">
        <span class="sc_title_header">
            @L["Index_Welcome"]
        </span>
        <div class="sc_slider sc_slider_style_1 sc_slider_swiper sc_slider_controls swiper-container sc_slider_swiper_autoheight">
            <ul class="slides swiper-wrapper" data-settings="none">
                <li class="swiper-slide slider_image_1" data-theme="dark"></li>
                <li class="swiper-slide slider_image_2" data-theme="dark"></li>
                <li class="swiper-slide slider_image_3" data-theme="dark"></li>
                <li class="swiper-slide slider_image_4" data-theme="dark"></li>
                <li class="swiper-slide slider_image_5" data-theme="dark"></li>
                <li class="swiper-slide slider_image_6" data-theme="dark"></li>
                <li class="swiper-slide slider_image_7" data-theme="dark"></li>
                <li class="swiper-slide slider_image_8" data-theme="dark"></li>
            </ul>
            <ul class="slider-control-nav">
                <li class="slide-prev">
                    <a class="icon-left-open-big" style="text-decoration: none;" href="#"></a>
                </li>
                <li class="slide-next">
                    <a class="icon-right-open-big" style="text-decoration: none;" href="#"></a>
                </li>
            </ul>
        </div>
    </div>
</section>

SRC/Applications/HomePage.Web/Views/Shared/_Social.cshtml
<div class="sc_line  sc_line_style_dotted"></div>
<h4>Share</h4>

<a href="#" class="fa fa-facebook"></a>
@*<a href="#" class="fa fa-twitter"></a>
<a href="#" class="fa fa-google"></a>
<a href="#" class="fa fa-linkedin"></a>*@
<a href="#" class="fa fa-instagram"></a>
<a href="#" class="fa fa-zalo">
    <img src="~/images/zalo.png"/>
</a>

SRC/Applications/HomePage.Web/Views/Shared/_cart_product.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@inject IHtmlLocalizer<SharedResource> L

<li class="usermenuCart">
    <a class="" href="@L["R.Cart"]">
        <i class="fa fa-shopping-cart" style="font-size:14px"></i> @L["Cart"]
        <span class="badge" style="font-size:13px; color:white; font-weight:normal;">0</span>
    </a>
</li>